name: saudi_clean_services_delivery
description: Saudi Clean Services Delivery

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  file_picker: ^5.0.1
  url_launcher: ^6.1.6
  syncfusion_flutter_gauges: ^20.3.58
  fl_chart: ^0.55.2
  # image: ^3.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

#adding the splash screen
flutter_native_splash:
  background_image: assets/images/splash.png

#adding the app icon
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_logo.jpg



flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/splash.png
    - assets/images/app_logo.jpg
    - assets/images/background.jpg
    - assets/images/start.png



  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700


